[package]
name = "weechat-sys"
version = "0.1.1"
authors = [
    "KokaKiwi <kokakiwi@kokakiwi.net>",
    "Damir Jelić <poljar@termina.org.uk>"
]
description = "Rust low level API bindings for Weechat"
license = "MIT"
edition = "2018"

[build-dependencies]
bindgen = { version = "0.55.1", default-features = false }

[dependencies]
libc = "0.2.69"
